runtime: nodejs20

entrypoint: node src/backend/server.js

env_variables:
  NODE_ENV: production
  JWT_SECRET: '${{ secrets.JWT_SECRET }}'
  DATABASE_URL: '${{ secrets.DATABASE_URL }}'

automatic_scaling:
  max_instances: 2
