name: Deploy App

on:
  push:
    branches: [ main ]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Install Node
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install packages
      run: npm ci
    
    - name: Prepare application
      run: |
        npx prisma generate
        npm run build
        npm run asbuild
    
    - name: Connect GCP
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}
    
    - name: Setup gcloud
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: cs144-25s-yurikim
    
    - name: Final Deploy
      run: |
        gcloud app deploy --quiet \
          --set-env-vars="JWT_SECRET=${{ secrets.JWT_SECRET }},DATABASE_URL=${{ secrets.DATABASE_URL }}"